name: dart
description: >-
  sadece eÄŸitim amaÃ§lÄ± notlar
version: 0.0.7
homepage: https://example-pet-store.com/newtify
documentation: https://example-pet-store.com/newtify/docs

environment:
  sdk: '>=2.12.0'
  
dependencies:

  
dev_dependencies:
  test: ^1.24.3
